#!/usr/bin/env python3
"""Merge catalog/*.json with data/resolved.json into data/scenes.json and data/scenes.js.

    python3 tools/build.py                      # write data/scenes.json + data/scenes.js
    python3 tools/build.py --standalone out.html

--standalone writes a single self-contained page: data inlined, thumbnails embedded as WebP
data URIs (needs ffmpeg), and clips that open on YouTube at the window's start instead of the
embedded player. Use it where YouTube embeds or remote images are not allowed.
"""
import argparse
import base64
import json
import re
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from resolve import RESOLVED, ROOT, load_catalog  # noqa: E402

import requests  # noqa: E402

DATA = ROOT / "data"
FIELDS = ["id", "film", "year", "scene", "category", "medium", "country", "director", "craft",
          "accolades", "techniques", "why"]
CLIP_FIELDS = ["video", "title", "channel", "duration", "views", "start", "end", "pick", "heat", "alts"]


def merged():
    resolved = json.loads(RESOLVED.read_text()) if RESOLVED.exists() else {}
    scenes, missing = [], []
    for scene in load_catalog():
        clip = resolved.get(scene["id"], {})
        if clip.get("status") != "ok":
            missing.append(scene["id"])
            continue
        row = {k: scene.get(k) for k in FIELDS}
        row.update({k: clip.get(k) for k in CLIP_FIELDS})
        scenes.append(row)
    return scenes, missing


def thumb_data_uri(video_id, cache_dir):
    out = cache_dir / f"{video_id}.webp"
    if not out.exists():
        r = requests.get(f"https://i.ytimg.com/vi/{video_id}/mqdefault.jpg", timeout=30)
        r.raise_for_status()
        src = cache_dir / f"{video_id}.jpg"
        src.write_bytes(r.content)
        subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(src), "-vf", "scale=288:-2",
                        "-quality", "52", str(out)], check=True)
    return "data:image/webp;base64," + base64.b64encode(out.read_bytes()).decode()


def standalone(scenes, path):
    page = (ROOT / "index.html").read_text()
    body = page.split("<!-- @artifact-start -->", 1)[1].split("<!-- @artifact-end -->", 1)[0]
    body = re.sub(r"<!-- @head-end -->\s*</head>\s*<body>", "", body)
    cache = Path(tempfile.gettempdir()) / "scene-library-thumbs"
    cache.mkdir(exist_ok=True)
    with ThreadPoolExecutor(8) as pool:
        uris = list(pool.map(lambda s: thumb_data_uri(s["video"], cache), scenes))
    thumbs = {s["video"]: uri for s, uri in zip(scenes, uris)}
    def js(value):  # JSON that cannot close the surrounding <script> element
        return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

    data = (f"<script>window.SL_MODE='link';window.SCENE_DATA={js({'scenes': scenes})};"
            f"window.SCENE_THUMBS={js(thumbs)};</script>")
    body = body.replace('<script src="data/scenes.js"></script><!-- @data -->', data)
    Path(path).write_text(body.strip() + "\n")
    print(f"wrote {path} ({Path(path).stat().st_size / 1e6:.1f} MB, {len(scenes)} scenes)")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--standalone", metavar="OUT.html")
    args = ap.parse_args()

    scenes, missing = merged()
    DATA.mkdir(exist_ok=True)
    payload = {"scenes": scenes}
    (DATA / "scenes.json").write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n")
    (DATA / "scenes.js").write_text(
        "// Generated by tools/build.py from catalog/*.json and data/resolved.json. Do not edit.\n"
        f"window.SCENE_DATA = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n")
    print(f"{len(scenes)} scenes with clips, {len(missing)} without")
    for m in missing:
        print(f"  no clip: {m}")
    if args.standalone:
        standalone(scenes, args.standalone)


if __name__ == "__main__":
    main()
